---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cx-operator
  namespace: landscape-apps
spec:
  interval: 5m
  url: https://cgx.jfrog.io/artifactory/coralogix-charts-virtual

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cx-operator
  namespace: landscape-apps
spec:
  interval: 10m0s
  timeout: 5m
  chart:
    spec:
      chart: coralogix-operator
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: cx-operator
      interval: 1m
  releaseName: cx-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    secret:
      data:
        apiKey: "${CX_API_KEY}"
    coralogixOperator:
      region: "EU2"
  