apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: landscape-apps
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: landscape
  path: "./packages/base/apps"
  prune: false
  timeout: 1m