apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: landscape-apps
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: landscape-apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./packages/base/apps"
  prune: false
  timeout: 1m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: coralogix-secret-keys