apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: landscape-misc
  namespace: flux-system
spec:
  dependsOn:
    - name: landscape-apps
      namespace: landscape-apps
  interval: 5m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./packages/base/misc"
  prune: false
  timeout: 1m